### PR TITLE
Add ability to set a custom callback after `AfterRegistrator` runs

### PR DESCRIPTION
**Pull request by trestrantham**
I am using this to kick off additional registration tasks after ueberauth creation has completed and thought it might be worth adding formally. Let me know if you have any feedback. 🤘

### CODE REVIEW

**Comment by britton-jb** [comment]
Sweet. I will have some time to look at this one in the next few days. I'll let you know if there are any changes that need made.

I really appreciate you taking the time to put up this PR, and it seems like this is likely worthwhile.

**Comment by britton-jb** [comment]
This is looking good. I'd like to add a spec for this if possible ensuring that the interface works, and to prevent this feature from being accidentally broken, but otherwise I'm feeling very good about this PR.

**Comment by trestrantham** [comment]
Sweet. I'll add specs for this and for https://github.com/britton-jb/sentinel/pull/40 hopefully this evening.

**Comment by trestrantham** [comment]
Specs added 🚦

**Review by britton-jb — APPROVED** [review]

**Pull request merged**
