### PR TITLE
Add ability to generate and copy views and templates into the application

### PR DESCRIPTION
**Pull request by trestrantham**
I had a need to customize the default registration views (by adding additional user fields) and needed a way to copy the views/templates into my application as a result.

This copies sentinel views and templates into the application for a given context using `mix sentinel.gen.views user`. Available values are "email", "error", "password", "session", "shared", and "user". To support this, all views have been parameterized and added to `Config.views`. Once a given view (and templates) has been copied to the application, the view must be specified in `config.exs` using the `views` key:

```elixir
config :sentinel,
  views: %{user: MyApp.Web.UserView}
```

### CODE REVIEW

**Comment by trestrantham** [comment]
Just pushed a commit to make these generators compatible with `phoenix <= 1.2` 🕺

**Comment by rrevanth** [comment]
I tested this branch in my pheonix 1.2 application and it's working as expected.

I just updated the views config in my application to corresponding modules.

**Comment by trestrantham** [comment]
Fixed a bug with the password view generation and updated README (hat tip to @rrevanth). I don't have anything else pending here, so let me know if you catch anything @britton-jb. 🕵️

**Comment by britton-jb** [comment]
I'll take some time to review this (and the other PRs) one more time tonight, but I really appreciate the work you've done, and @rrevanth for testing.

**Comment by trestrantham** [comment]
Updated this with latest `master` 👍

**Comment by britton-jb** [comment]
Sorry this one is taking me longer to get to, but thanks again for all of the other work you've done so far.

**Comment by trestrantham** [comment]
No worries! I working with this locally so no rush on my end.

**Comment by trestrantham** [comment]
Is there anything I can do to help this get merged?

**Comment by britton-jb** [comment]
This one is actually good, and upon reflection I should have just merged it in already. I just have bit more I want to do on my side before I release a new version of Sentinel to Hex with these breaking API changes.

Sorry about the delays.

**Comment by trestrantham** [comment]
No worries. Let me know if there's anything I can help with whether it be this PR or elsewhere. 🙌

**Pull request merged**
