### PR TITLE
Customizeable redirects for HTML controllers

### PR DESCRIPTION
**Pull request by Draiken**
Adding a proper way to customize redirects for the HTML controllers.

This still needs tests, but I think this would be best tested on the controller level. Not sure if you agree

This also changes the redirect path after a confirmation signup to the "confirmation_instructions" path

### CODE REVIEW

**Comment by britton-jb** [comment]
👍 This is a much better way to handle the redirection than my original cut. Fantastic work.

I'd like to get specs included with this before we merge it in, so I'll see if I can add them today. If you beat me to it that's awesome as well. Either way let's get those added and then we can add this in and I'll increment the version in the hex package and update the change log.

**Comment by Ch4s3** [comment]
What's up with this PR?

**Comment by Draiken** [comment]
I've stopped using Sentinel for my project and ended up not finishing this. I think it just needs to fix the tests, so anyone can finish this work if it's still relevant.

**Comment by britton-jb** [comment]
@Ch4s3 It needs some serious TLC on the HTML side, which I'm working on, along with some general logic fixes for V2, but I need to add a note to the README that this is slow in the coming. Once again thanks to @Draiken for the stuff he's contributed to Sentinel.

**Pull request closed without merging**
