### PR TITLE
Fix bug in ueberauthenticator and Add test for it, resolves #51

### LINKED ISSUE #51: Code Error when authenticating through third party provider (i.e. Github)
Hi, I tried using Github to authenticate in an app I'm building and I failed so I tried the sentinel_example you made and it also failed.

error

### PR DESCRIPTION
**Pull request by demiJade**
Resolves issue #51 

I changed `auth.info.email` to `auth_params.info.email` in line 61 of ueberauthenticator.ex.

I also added a test for that.

### CODE REVIEW

**Comment by britton-jb** [comment]
Thanks for sending this in. Hopefully I'll be able to look at it later today, but I really appreciate the PR, especially with tests. Sorry about the slow reply.

**Comment by cubeguerrero** [comment]
Any updates on this?

**Review by britton-jb — APPROVED** [review]

**Comment by britton-jb** [comment]
Sorry this took me so long. Excellent work on finding the defect and patching it here, with a spec. I really appreciate it.

**Comment by demiJade** [comment]
Thanks! 😊

**Pull request merged**
